### ISSUE TITLE
Compile errors when building with Android NDK22

### ISSUE THREAD

**Issue by rockaport** [thom311/libnl#279] opened 2021-04-25 03:20 UTC
I'm getting various header issues when compiling with the latest Android NDK. This doesn't appear to be an issue with 3.25.

```
  CC       route/link/ipgre.lo
  CC       route/link/sit.lo
  CC       route/link/ipvti.lo
  CC       route/link/ip6tnl.lo
In file included from ../../lib/cache.c:52:
In file included from ../../include/netlink-private/netlink.h:33:
/home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/arpa/inet.h:39:1: error: unknown type name 'in_addr_t'
in_addr_t inet_addr(const char* __s);
^
/home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/arpa/inet.h:43:1: error: unknown type name 'in_addr_t'
in_addr_t inet_lnaof(struct in_addr __addr) __INTRODUCED_IN(21);
^
```

```
In file included from ../../lib/msg.c:29:
In file included from ../../include/netlink-private/netlink.h:63:
In file included from ../../include/netlink/netlink.h:29:
In file included from /home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/arpa/inet.h/home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/netinet/tcp.h::36:
/home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/linux/tcp.h:228:27: error: field has incomplete type 'struct sockaddr_storage'
44:30  struct sockaddr_storage tcpm_addr;
                          ^
:/home/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/linux/tcp.h:228:10:  note: forward declaration of 'struct sockaddr_storage'
  struct sockaddr_storage tcpm_addr;
         ^

```

**Comment by thom311** [comment] 2022-03-14 23:41
I don't know why this happens and I don't have access to such a build environment.

Also, you don't say which version was tested. The failure seems to refer to `include/netlink-private/netlink.h:33`, but there isn't anything interesting there -- at the libnl version that was current when the issue was reported.

If you still can reproduce this, please provide more information and reopen. Closing for now, thank you

**Closed by thom311** 2022-03-14 23:41 UTC

**Comment by mcheng89** [comment] 2022-07-11 03:25
The error seems to be due to differences in the linux/in.h file for Android NDK:

https://android.googlesource.com/toolchain/prebuilts/ndk/r21/+/refs/heads/androidx-autofill-release/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/linux/in.h#23
`
#include <bits/in_addr.h>
 `

The bits/in_addr.h file defines the in_addr_t:
https://android.googlesource.com/toolchain/prebuilts/ndk/r21/+/refs/heads/androidx-autofill-release/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/in_addr.h


This differs from the linux/in.h that is included in this repo:
https://github.com/thom311/libnl/blob/main/include/linux-private/linux/in.h

When I removed this include, the NDK was able to compile libnl successfully.

**Comment by xueshenan** [comment] 2023-11-09 07:04
I have the same issue on compile libnl with android ndk. @mcheng89 , what is the include file is removed?

**Comment by thom311** [comment] 2024-01-20 14:42
> Almost three years, same issues. If API Level >= 26 (Android 8), you only need:

Just to be clear, this issue is not present on this repository. Report it to the place that keeps the fork of libnl3 (Android?)

Of course, it's helpful here to comment so that people can find out about the problem. Thanks for that.

**Comment by longbai** [comment] 2024-12-25 05:30
➜  iproute2 git:(main) ✗ make CROSS_COMPILE=$TOOLCHAIN/bin/aarch64-linux-android- PLATFORM=android V=1

lib
make[1]: Entering directory '/home/bailong/iproute2/lib'
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -Wall -Wstrict-prototypes  -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wformat=2 -O2 -pipe -I../include -I../include/uapi -DRESOLVE_HOSTNAMES -DLIBDIR=\"/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib\" -DCONF_USR_DIR=\"/usr/share/iproute2\" -DCONF_ETC_DIR=\"/etc/iproute2\" -DNETNS_RUN_DIR=\"/var/run/netns\" -DNETNS_ETC_DIR=\"/etc/netns\" -DARPDDIR=\"/var/lib/arpd\" -DCONF_COLOR=COLOR_OPT_NEVER -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DHAVE_SETNS -DHAVE_HANDLE_AT -DHAVE_ELF  -DNEED_STRLCPY --sysroot=/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_SETNS -DHAVE_HANDLE_AT -DHAVE_ELF  -DNEED_STRLCPY --sysroot=/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC   -c -o libnetlink.o libnetlink.c
libnetlink.c:152:2: warning: "libmnl required for error support" [-W#warnings]
#warning "libmnl required for error support"
 ^
1 warning generated.
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar rcs libnetlink.a libgenl.o libnetlink.o
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -Wall -Wstrict-prototypes  -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wformat=2 -O2 -pipe -I../include -I../include/uapi -DRESOLVE_HOSTNAMES -DLIBDIR=\"/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib\" -DCONF_USR_DIR=\"/usr/share/iproute2\" -DCONF_ETC_DIR=\"/etc/iproute2\" -DNETNS_RUN_DIR=\"/var/run/netns\" -DNETNS_ETC_DIR=\"/etc/netns\" -DARPDDIR=\"/var/lib/arpd\" -DCONF_COLOR=COLOR_OPT_NEVER -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DHAVE_SETNS -DHAVE_HANDLE_AT -DHAVE_ELF  -DNEED_STRLCPY --sysroot=/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_SETNS -DHAVE_HANDLE_AT -DHAVE_ELF  -DNEED_STRLCPY --sysroot=/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC   -c -o utils.o utils.c
utils.c:541:7: error: member reference base type '__u32' (aka 'unsigned int') is not a structure or union
                if (IN6_IS_ADDR_UNSPECIFIED(addr->data))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/netinet/in6.h:37:9: note: expanded from macro 'IN6_IS_ADDR_UNSPECIFIED'
  ((((a)->s6_addr32[0]) == 0) && \
     ~~~^ ~~~~~~~~~
utils.c:541:7: error: member reference base type '__u32' (aka 'unsigned int') is not a structure or union
                if (IN6_IS_ADDR_UNSPECIFIED(addr->data))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/netinet/in6.h:38:9: note: expanded from macro 'IN6_IS_ADDR_UNSPECIFIED'
   (((a)->s6_addr32[1]) == 0) && \
     ~~~^ ~~~~~~~~~
utils.c:541:7: error: member reference base type '__u32' (aka 'unsigned int') is not a structure or union
                if (IN6_IS_ADDR_UNSPECIFIED(addr->data))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/netinet/in6.h:39:9: note: expanded from macro 'IN6_IS_ADDR_UNSPECIFIED'
   (((a)->s6_addr32[2]) == 0) && \
     ~~~^ ~~~~~~~~~
utils.c:541:7: error: member reference base type '__u32' (aka 'unsigned int') is not a structure or union
                if (IN6_IS_ADDR_UNSPECIFIED(addr->data))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bailong/android-ndk-r23/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/netinet/in6.h:40:9: note: expanded from macro 'IN6_IS_ADDR_UNSPECIFIED'
   (((a)->s6_addr32[3]) == 0))
     ~~~^ ~~~~~~~~~
utils.c:1112:3: warning: implicit declaration of function 'sethostent' is invalid in C99 [-Wimplicit-function-declaration]
                sethostent(1);
                ^
1 warning and 4 errors generated.
make[1]: *** [../config.mk:46: utils.o] Error 1
